# Generated by Django 5.2 on 2025-05-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='categoria',
            field=models.CharField(choices=[('masajes', 'Masajes'), ('belleza', 'Belleza'), ('faciales', 'Faciales'), ('corporal', 'Corporal'), ('grupal', 'Grupal')], default='masajes', max_length=20),
        ),
    ]
