# Generated by Django 5.2 on 2025-04-19 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0001_initial'),
        ('Turnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnos',
            name='servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Servicios.servicios'),
            preserve_default=False,
        ),
    ]
