# Generated by Django 5.2 on 2025-04-23 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0001_initial'),
        ('Turnos', '0003_remove_turnos_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnos',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='turnos',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='turnos',
            name='servicio',
        ),
        migrations.AlterField(
            model_name='turnos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='HorarioDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('disponible', models.BooleanField(default=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicios.servicios')),
            ],
        ),
        migrations.AddField(
            model_name='turnos',
            name='horario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Turnos.horariodisponible'),
            preserve_default=False,
        ),
    ]
